export const yupErrorsConstant = {
  required: 'الزامی است',
  numberBase: 'مقدار باید عدد باشد',
  numberBaseZero: 'مقدار باید عدد بزرگتر از صفر باشد',
  stringBase: 'فقط مقادیر رشته‌ای مجاز است',
  arrayBase: 'فقط آرایه مجاز است',
  objectBase: 'فقط آبجکت مجاز است',
  persian: 'فقط حروف فارسی مجاز است',
  english: 'فقط حروف انگلیسی مجاز است',
  numeric: 'فقط اعداد مجاز است',
  email: 'ایمیل نامعتبر است',
  url: 'آدرس URL نامعتبر است',
  phone: 'شماره تلفن نامعتبر است',
  boolean: 'مقدار باید بولین باشد',
  positive: 'مقدار باید مثبت باشد',
  percentage: 'درصد باید بین 0 تا 100 باشد',
  uniqueArray: 'آیتم‌ها باید یکتا باشند',
  noUnknown: 'فیلدهای ناشناخته مجاز نیستند',
  min: 'حداقل یک مورد را انتخاب کنید',
  stringMin: (length: number) => `حداقل ${length} حرف مجاز است`,
  stringMax: (length: number) => `حداکثر ${length} حرف مجاز است`,
  arrayMin: (length: number) => `حداقل ${length} آیتم الزامی است`,
  arrayMax: (length: number) => `حداکثر ${length} آیتم مجاز است`,
  numberMin: (min: number) => `مقدار باید حداقل ${min} باشد`,
  numberMax: (max: number) => `مقدار باید حداکثر ${max} باشد`,
  dateBase: 'تاریخ نامعتبر است',
  dateMin: (date: string) => `تاریخ باید بعد از ${date} باشد`,
  dateMax: (date: string) => `تاریخ باید قبل از ${date} باشد`,
  matches: 'فرمت ورودی نامعتبر است',
  oneOf: 'مقدار باید یکی از مقادیر مجاز باشد',
  notOneOf: 'مقدار نباید یکی از مقادیر غیرمجاز باشد',
  custom: (message: string) => message,
};
